version: '3'
services:
  frontend:
    image: node:14.18.1
    working_dir: '/app/frontend'
    environment:
      - HOST=0.0.0.0
    ports:
      - '80:3000'
    volumes:
      - ./frontend:/app/frontend
    command: bash -c "npm install && npm run dev"
